[package]
name = "main"
version = "0.1.0"
edition = "2021"
authors = ["James Dean"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }

server = { path = "../server" }

config = { path = "../config" }